# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Kshitij Raj Lohani"
description: > # this means to ignore newlines until "email:"
   Personal Website of Kshitij Raj Lohani

#email: k[dot]lohani[01]@[google email service provider]
#blog logo
logo: "/assets/images/kshitij_profile_pic_sf_gbridge.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Kshitij Raj Lohani'
author: 'Kshitij Raj Lohani'
author_image: "/assets/images/kshitij_profile_pic.jpg"

paginate:	5

url: "https:kshitijlohani.com" # the base hostname & protocol for your site
baseurl: ""
imageurl: "/assets/images"
#used to display twitter cards
twitter_handle: '@kshitij_lohani'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	facebook
    url:	https://www.facebook.com/kshitij.lohani

  - icon:	twitter
    url:	https://twitter.com/kshitij_lohani

  - icon:	youtube
    url:	https://www.youtube.com/channel/UCIPTTIR6OEa8wAdABoEj3zg

  - icon:	instagram
    url:	https://www.instagram.com/kshitij.lohani/
